<?php

$config = include '/app/config.php';
require_once 'vendor/autoload.php';

use GuzzleHttp\Client as GuzzleHttpClient;
use Krizalys\Onedrive\Client;
use Microsoft\Graph\Graph;
use Monolog\Logger;

function getFileOrFolderId($children, $type, $name) {
	foreach($children as $i => $child){
		$tmpFile = $child->file;
		$tmpFolder = $child->folder;

		//check for drive item type based on $type arg
		$isFolder = ($tmpFile === NULL) && ($tmpFolder != NULL);
		$typeCheck = $type === "folder" ? $isFolder : !$isFolder;
		
		//check if item is file/folder and has custom name specified above and if exists retrive it's id and return it
		if( $typeCheck && strcmp($child->name, $name)==0) {
			return $child;
		}
	}
	return NULL;
}


if($argc < 3){
	die("Invalid script invocation");
}

$videoFileName = $argv[1];
$authCode = $argv[2];

$client = new Krizalys\Onedrive\Client(
	$config['ONEDRIVE_CLIENT_ID'],
    new Microsoft\Graph\Graph(),
    new GuzzleHttp\Client(
        ['base_uri' => 'https://graph.microsoft.com/v1.0/']
    ),
    new Monolog\Logger('Krizalys\Onedrive\Client')
);

$oauthUrl = $client->getLogInUrl([
    'files.read',
    'files.read.all',
    'files.readwrite',
    'files.readwrite.all',
    'offline_access',
], $config['ONEDRIVE_REDIRECT_URI']);

$client->obtainAccessToken($config['ONEDRIVE_CLIENT_SECRET'], $authCode);

//Get all drives
$drives = $client->getDrives();

//Select personal drive
$rootDrive = $drives[0]->getRoot();

//Get drive items
$children = $rootDrive->getChildren();

$folderList = array();
$folderName="HotstarVideos";
$folderId=NULL;

$folder=getFileOrFolderId($children, "folder", $folderName);

if($folder === NULL){
	$driveItemProxy = $rootDrive->createFolder($folderName, ['description' => 'Hotstar videos generated by downloader']);
	$folderId = $driveItemProxy->id;
} else {
	$folderId = $folder->id;
}

echo PHP_EOL."Folder name : ".$folderName;
echo PHP_EOL."Folder id : ".$folderId;

?>